<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DataModel" nsURI="http://www.eclipse.org/ReqCycle/DataModel"
    nsPrefix="DataModel">
  <eClassifiers xsi:type="ecore:EClass" name="RequirementSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Contained" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStringToStringMapEntry"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectorID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" upperBound="-1"
        eType="ecore:EClass MappingModel.ecore#//ElementMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contained" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="hidden"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scopes" upperBound="-1"
        eType="#//Scope" eOpposite="#//Scope/requirements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReachableSection" eSuperTypes="#//Contained">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Contained" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReachableObject" eSuperTypes="#//Contained"/>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//ReachableObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementSection" eSuperTypes="#//ReachableObject #//ReachableSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Scope" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Contained" eOpposite="#//Contained/scopes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//Scope"/>
  <eClassifiers xsi:type="ecore:EClass" name="Customer" eSuperTypes="#//Scope"/>
</ecore:EPackage>
